#!/usr/bin/env bash


containerName="zig-dev-${USER}"
imageName="zig-dev-${USER}"

echo "Running docker create"

docker create -it --gpus=all \
         --name $containerName \
         --net host \
         --privileged \
         --shm-size 4G \
         --user $USER \
         -v $HOME/:$HOME \
         -v /tmp/.X11-unix:/tmp/.X11-unix \
         -e DISPLAY=$DISPLAY \
         -e XAUTHORITY \
         -e CONTAINER_NAME=$containerName \
         -h $containerName $imageName
