#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

VUNDLE=~/.vim/bundle/Vundle.vim
if [ -d "$VUNDLE" ]; then rm -Rf $VUNDLE; fi
git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE

cp ${SCRIPT_DIR}/vimrc  ~/.vimrc

vim +PluginInstall +qall
vim +PlugInstall +qall

python3 ~/.vim/bundle/YouCompleteMe/install.py --clang-completer --rust-completer

vim +PluginInstall +qall

sudo apt-get install ripgrep

cat << EOF > ~/.tmux.conf
set -g default-terminal "xterm"
EOF

RUST_ANALYZER=~/.local/bin/rust-analyzer 
if [ -f "$RUST_ANALYZER" ]; then rm -Rf $RUST_ANALYZER; fi

mkdir ~/.local/bin 
curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > $RUST_ANALYZER
chmod +x $RUST_ANALYZER
