#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cat <<EOF > ~/.aliases
alias clion='~/clion/bin/clion.sh'

alias gl='/home/kevin/repos/dev_env/opengl/run'
alias gl-setup='/home/kevin/repos/dev_env/opengl/gl-setup'

alias serenity='/home/kevin/repos/dev_env/serenity/run'
alias serenity-setup='/home/kevin/repos/dev_env/serenity/serenity-setup'

alias gcc-dev='/home/kevin/repos/dev_env/gcc/run'
alias gcc-dev-setup='/home/kevin/repos/dev_env/gcc/gcc-setup'

alias clang-dev='/home/kevin/repos/dev_env/clang/run'
alias clang-dev-setup='/home/kevin/repos/dev_env/clang/clang-setup'

alias rust_env='/home/kevin/repos/dev_env/rust_env/run'
alias rust_env-setup='/home/kevin/repos/dev_env/rust_env/rust-setup'
alias tmux='TERM=screen-256color-bce tmux'

alias ls="exa"
alias gs="git status"
alias gpl="git pull"
alias gpsh="git push"
EOF


if grep -Fxq "source ~/.aliases" ~/.bashrc
then
    echo "Aliases already setup in .bashrc"
else
    echo "Installing aliases in .bashrc"
    echo "source ~/.aliases" >> ~/.bashrc
fi

if grep -Fxq "source ~/.aliases" ~/.zshrc
then
    echo "Aliases already setup in .zshrc"
else
    echo "Installing aliases in .zshrc"
    echo "source ~/.aliases" >> ~/.zshrc
fi
