#!/usr/bin/env bash

rm -f -- ~/.vimrc

sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim-gtk3

echo "set number" >> ~/.vimrc

cat <<EOF >> ~/.vimrc
function FormatBuffer()
  if &modified && !empty(findfile('.clang-format', expand('%:p:h') . ';'))
    let cursor_pos = getpos('.')
    :%!clang-format
    call setpos('.', cursor_pos)
  endif
endfunction

autocmd BufWritePre *.h,*.hpp,*.c,*.cpp,*.vert,*.frag :call FormatBuffer()
EOF

echo "set encoding=utf-8" >> ~/.vimrc
