#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install zsh


OMZ=~/.oh-my-zsh

if [ -d "$OMZ" ]; then rm -Rf $OMZ; fi

ZSH= sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

